# Generated by Django 4.2.23 on 2025-06-28 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("HIREBASE", "Hirebase"), ("RAPIDAPI", "RapidAPI")],
                        default="HIREBASE",
                        max_length=10,
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("application_link", models.TextField()),
                ("date_posted", models.DateTimeField()),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("date_validthrough", models.DateTimeField(blank=True, null=True)),
                ("employment_type", models.JSONField(blank=True, null=True)),
                (
                    "location_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remote_derived", models.BooleanField(default=False)),
                ("visa_sponsored", models.BooleanField(default=False)),
                ("source_type", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("source_domain", models.TextField(blank=True, null=True)),
                ("requirements_raw", models.JSONField(blank=True, null=True)),
                ("location_requirements_raw", models.JSONField(blank=True, null=True)),
                ("salary_raw", models.JSONField(blank=True, null=True)),
                ("locations_alt_raw", models.JSONField(blank=True, null=True)),
                ("locations_raw", models.JSONField(blank=True, null=True)),
                ("locations_derived", models.JSONField(blank=True, null=True)),
                ("cities_derived", models.JSONField(blank=True, null=True)),
                ("regions_derived", models.JSONField(blank=True, null=True)),
                ("countries_derived", models.JSONField(blank=True, null=True)),
                ("timezones_derived", models.JSONField(blank=True, null=True)),
                ("lats_derived", models.JSONField(blank=True, null=True)),
                ("lngs_derived", models.JSONField(blank=True, null=True)),
                ("organization", models.TextField(blank=True, null=True)),
                ("organization_url", models.TextField(blank=True, null=True)),
                ("organization_logo", models.TextField(blank=True, null=True)),
                ("domain_derived", models.TextField(blank=True, null=True)),
                ("meta", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
