# Generated by Django 4.2.23 on 2025-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="company_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="hirebase_job_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_board",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_board_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_categories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="locations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="yoe_range",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
