# Generated by Django 4.2.23 on 2025-06-30 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0002_job_company_data_job_company_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_type",
        ),
    ]
