# Generated by Django 4.2.23 on 2025-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0005_job_company_data_job_company_slug_job_job_meta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_slug",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_meta",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_slug",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="score",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
